export const patientTheme = {
  colors: {
    background: '#F7F8FB',
    surface: '#FFFFFF',
    elevated: '#FBFCFF',
    primary: '#2962FF',
    primaryDark: '#1F4FD8',
    primarySoft: '#E4EBFF',
    accent: '#1E88E5',
    success: '#22C55E',
    warning: '#F97316',
    danger: '#EF4444',
    info: '#0EA5E9',
    textPrimary: '#0F172A',
    textSecondary: '#556080',
    textMuted: '#94A3B8',
    border: '#E2E8F0',
    cardBorder: '#EEF2FF',
    shadow: 'rgba(15, 23, 42, 0.08)',
    lightIcon: '#4C6FFF',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
  },
  radii: {
    sm: 10,
    md: 14,
    lg: 20,
    pill: 999,
  },
  typography: {
    header: 24,
    title: 18,
    body: 15,
    small: 13,
  },
  shadow: {
    card: {
      shadowColor: 'rgba(15, 23, 42, 0.12)',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 6,
    },
  },
  icons: {
    headerNotification: 'notifications-outline',
    search: 'search-outline',
    clear: 'close-outline',
    doctor: 'medkit-outline',
    location: 'location-outline',
    distance: 'navigate-outline',
    calendar: 'calendar-outline',
    time: 'time-outline',
    clinic: 'business-outline',
    chatSend: 'paper-plane-outline',
    language: 'globe-outline',
    logout: 'log-out-outline',
  },
};
